### ISSUE TITLE
commit id too long

### ISSUE THREAD

**Issue by zzuzhp** [ansemjo/version.sh#4]
in most cases a full 40 chars long commit id is not necessary, the leading 7 chars is long enough to distinguish it from others.
also, you limit the length to 7 by 'printf '%s%s%.7s\n' "$(version)" "$COMMIT_SEPERATOR" "$(commit)";' what if working space is dirty? (the "-dirty" will be truncated)

so why not using --abbrev=7 in git describe ?
also, to make it more brief, i think '--dirty=M --broken=W' is better than just '--dirty'.

**Comment by ansemjo** [comment]
Thanks for these issues! I'm glad if it's actually useful to somebody.

> in most cases [...] the leading 7 chars is long enough to distinguish it from others

That's true but I wouldn't want to limit the commit output to 7 characters as it's trivial to do that with a pipe like `sh version.sh commit | head -c 7` or assign the output to a variable and use a custom printf format. I'd rather print all information that I have.

> so why not using --abbrev=7 in git describe ?

When using `version.sh` for a describe-like string, it is limited to 7 characters, as you have identified by the printfs format. `version.sh commit` output is more akin to `git rev-parse HEAD` .. which would be an argument not to include the `-dirty` in the commit at all and instead include it in the `describe` string.

> also, to make it more brief, i think '--dirty=M --broken=W' is better than just '--dirty'

Nice! I didn't know you can specify your own markers. Is `M` and `W` a common choice for this?

A possible argument against using `--broken` is that it is unavailable in older versions of git. CentOS 7 still has git version 1.8.3 for example, which does not include this flag.

**Comment by zzuzhp** [comment]
Okay, you have decent reasons not to limit the commit id to 7 chars. but it's not my case, i will have to do it myself.
i just think of the default markers as too long, and wanna simplify them. Then two words come to my mind, so it's probably not common choices. 'M' stands for 'modified' and 'W' for 'Wrong' (here means a corrupted repo maybe).
finally, really nice script, you did great work, it really helps, thanks!

**Comment by ansemjo** [comment]
I've added commit 59b8468fd85e37764f69ed415f1e86908aea0eb0 and 88d0abe071b7b64273aa584ae3801a0a3ad8187d to partially address this issue.

The `-dirty` flag is now appended to the describe string and can be customized by setting `GIT_DIRTY_MARKER`:

```sh
$ date >> LICENSE 
$ sh version.sh 
version  : 0.3.0-4
commit   : 59b8468fd85e37764f69ed415f1e86908aea0eb0
describe : 0.3.0-4-g59b8468-dirty
$ GIT_DIRTY_MARKER=M sh version.sh describe
0.3.0-4-g59b8468M
```

---

I'm now thinking about adding a `getopts` parser to address the increasing complexity and then I might add a length flag for the commit. But actually I'd rather keep things as simple as possible.

**Comment by zzuzhp** [comment]
i also suggest to show the branch name somewhere.

**Comment by ansemjo** [comment]
I've opened a new issue for that suggestion but that is not as trivial to do consistently (see https://github.com/ansemjo/version.sh/issues/5#issuecomment-514679520).
