### ISSUE TITLE
add the branch name to output

### ISSUE THREAD

**Issue by ansemjo** [ansemjo/version.sh#5]
i also suggest to show the branch name somewhere.

_Originally posted by @zzuzhp in https://github.com/ansemjo/version.sh/issues/4#issuecomment-514672963_

---

Afaik, the branch name is always present in the subsituted `REFS` variable and can be trivially found if we're in a git repository.

**Comment by ansemjo** [comment]
> always present in the substituted `REFS`

It appears this assumption is false. The branch name is only included when the exported ref is the tip of a branch. See:

```sh
$ git init
Initialized empty Git repository in /tmp/tmp-naughty-yalow/.git/
$ cp .../version.sh .
$ echo 'version.sh export-subst' > .gitattributes
$ git add .
$ git commit -m init
[...]
$ git output HEAD version.sh | grep ^REFS
REFS='HEAD -> master'
$ git tag -a 1.0 -m test
$ git output HEAD version.sh | grep ^REFS
REFS='HEAD -> master, tag: 1.0'
$ git commit --allow-empty -m "$(date)"
[master cc3ae54] Wed 24 Jul 17:18:15 CEST 2019
$ git output HEAD version.sh | grep ^REFS
REFS='HEAD -> master'
$ git output 1.0 version.sh | grep ^REFS
REFS='tag: 1.0'   # <-- no branch name
```

So we can only use this information if we're working on the tip of a branch. But then it is already used for the version string as a fallback when it is not a tagged commit.

Maybe optionally allow printing the branch seperately and use a fallback value when it can't be parsed?

**Comment by zzuzhp** [comment]
i use 'symbolic-ref'

**Comment by ansemjo** [comment]
Yes, that's for the case of a checked-out repository. But an explicit goal of this script is to work equivalently from a downloaded tar archive and checked-out clone. In the former, it can't be guaranteed that the branch name is included in the substituted strings at all. Thus I cannot guarantee that I can output the correct branch name.
